[tool.poetry]
name = "pyradio"
version = "0.1.0"
description = "Python module for radio computation"
authors = ["Heliosphere Network"]
readme = "README.md"
packages = [
    { include = "pyradio", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.10"
numpy = ">=1.24.0,<3.0.0"
scipy = ">=1.10.0,<2.0.0"

[tool.poetry.group.test.dependencies]
pytest = ">=7.4.0"
pytest-cov = ">=4.1.0"

[tool.pytest.ini_options]
addopts = "-ra -q --cov=src --cov-report=term-missing"
testpaths = [
    "tests"
]
python_files = ["test_*.py"]
python_functions = ["test_*"]

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
]
show_missing = true
fail_under = 90

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
