name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

# Permissions required for GitHub Pages deployment
permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Build documentation
        run: |
          poetry run sphinx-build -b html docs/source docs/build/html

      - name: Upload Pages artifact
        id: upload-pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1